### ISSUE TITLE
Errors regarding the latest merge

### ISSUE THREAD

**Issue by dimeldo** [bme-chatbots/dialogue-generation#7]
First error:

```
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    main()
  File "run.py", line 68, in main
    create_dataset(args=args)
  File "/Downloads/GPT2/src/data.py", line 540, in create_dataset
    files = data_cls.download(args=args)
  File "/Downloads/GPT2/src/data.py", line 299, in download
    if args.local_rank in [-1, 0]:
AttributeError: 'Namespace' object has no attribute 'local_rank'
```

I just commented the if-check.

Then, another error:

```
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    from src.train import (
  File "/Downloads/GPT2/src/train.py", line 26, in <module>
    from src.data import (
  File "/Downloads/GPT2/src/data.py", line 38, in <module>
    from collate import COLLATE
ImportError: cannot import name 'COLLATE'
```

**Comment by Mrpatekful** [comment]
I have removed the local rank check but I am not sure what causes the import error. Have you run `python setup.py build_ext --inplace`? If so, then what python version are you using?

**Comment by dimeldo** [comment]
Yes, I ran the command. I'm using Python 3.6.8.

**Comment by dimeldo** [comment]
It also says this when running the command:

`Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
running build_ext`

Don't know if related.

**Comment by Mrpatekful** [comment]
From the error message it seems like your data.py version is different from the newest commit as it uses:

 `from collate import COLLATE` 

instead of 

`from src.collate import COLLATE`. 

If it is the case then please modify it to the latter and it should solve the import error. The issue is the package is not part of the sys.path for the Python interpreter and abosulte import from the root directory is required (`src.<filename>`).

**Comment by dimeldo** [comment]
You are right! That's weird that it happened. Sorry. And thanks so much for your efforts!
